version: '3'
services:
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  test:
    image: node:11
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./test:/app/test
      - ./package.json:/app/package.json
      - ./index.js:/app/index.js
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
